spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/myblog?useUnicode=true&amp;characterEncoding=UTF-8&amp;allowMultiQueries=true&amp;zeroDateTimeBehavior=convertToNull&amp;autoReconnect=true&amp;failOverReadOnly=false
    username: root
    password: fbmgr@#
    type: com.alibaba.druid.pool.DruidDataSource
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
logging:
  level:
    root:info
    com.github.fish:debug
  file: logs/blog-dev.log
server:
  port: 8080
#spring:
#  datasource:
#    druid:
#      filter:
#        slf4j:
#          enabled:true
#          statement-create-after-log-enabled:false
#          statement-close-after-log-enabled:false
#          result-set-open-after-log-enabled:false
#          result-set-close-after-log-enabled:false


