spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/myblog?useUnicode=true&amp;characterEncoding=UTF-8&amp;allowMultiQueries=true&amp;zeroDateTimeBehavior=convertToNull&amp;autoReconnect=true&amp;failOverReadOnly=false
    username: root
    password: Infrasys00@#
    type: com.alibaba.druid.pool.DruidDataSource
logging:
  level:
    root:warn
    com.github.fish:info
  file: logs/blog-pro.log
server:
  port: 8080
